server:
  port: 7006
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: login_route
          uri: lb://start-member
          predicates:
            - Path=/api/start/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: Img_router
          uri: lb://start-ims
          predicates:
            - Path=/api/img/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: Video_router
          uri: lb://start-vms
          predicates:
            - Path=/api/video/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

  application:
    name: start-getway
