server:
  port: 7005

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 419253381
    url: jdbc:mysql://localhost:3306/start_ims?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: start-ims
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 0
      logic-not-delete-value: 1